version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
#    image: docker.elastic.co/kibana/kibana:6.5.4
    image: elastic/kibana:6.5.4-wazuh_3.8
    depends_on:
      - elasticsearch
      - elasticsearch2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    hostname: kibana
    networks:
      - esnet
    ports:
      - 8080:5601
      - 8081:80
      - 9600:9600
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    depends_on:
      - elasticsearch
      - elasticsearch2
    ports:
      - 9700:9600
      - 5001:5000
      - 8082:80
    networks:
      - esnet
    volumes:
      - ./logstash/settings/:/usr/share/logstash/config/
      - ./logstash/data/:/data/

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
